# Generated by Django 3.2.6 on 2021-09-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Id', models.IntegerField()),
                ('Item_Category', models.CharField(max_length=100)),
                ('R_Id', models.IntegerField()),
                ('Order_Id', models.IntegerField()),
                ('Product_Id', models.IntegerField()),
            ],
        ),
    ]
