# Generated by Django 3.2.6 on 2021-09-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Itemshow',
        ),
    ]
