# Generated by Django 3.2.6 on 2021-10-01 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Itemshow',
        ),
    ]
