# Generated by Django 3.2.6 on 2021-10-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20211002_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='norder',
            name='tags',
        ),
        migrations.AddField(
            model_name='nproduct',
            name='tags',
            field=models.ManyToManyField(to='myapp.Tag'),
        ),
    ]
