# Generated by Django 3.2.6 on 2021-10-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20211002_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
