# Generated by Django 3.2.6 on 2021-10-02 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_nproduct_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NOrder',
        ),
    ]
