# Generated by Django 3.2.6 on 2021-10-02 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='tags',
        ),
    ]
